var redcount;
var greencount;
var d = new Array();
function createTable() {
  document.body.innerHTML += '<table border = 1 id="mytable"></table><br>';
  for (let i = 0; i < 4; i++) {
    document.getElementById("mytable").innerHTML += '<table border="1"><tr id="row' + i + '"></tr></table>';
    for (let k = 0; k < 4; k++) {
      document.getElementById("row" + i).innerHTML += '<td id=' + i + k + '></td>'; //Gives the (i,j)-cell of our table the id "concatenate(i,j)" for easier manipulation, we could do this
      //with an array generated by getElementsByClassName() but the id version is easier to debug and produces the same results
    }
  }
  document.body.innerHTML += '<div id="countdown"></div><div id="report"></div>';
}
function start() {
  init(); //initialize tickers, set cell colors to white
  document.getElementById("mybutton").disabled = true;
  fillTable();
  countdown(10);
  setTimeout(function () { redgreencountprint() }, 10000); //prints the counts after 10 sec
  var table = document.getElementById("mytable");
  if (table != null) {
    for (let i = 0; i < table.rows.length; i++) {
      for (let j = 0; j < table.rows[i].cells.length; j++)
        table.rows[i].cells[j].onclick = function () { colorChange(i, j); };
    }
  }//We made each cell clickable and gave it the onclick function of colorChange(i,j)
}
function fillTable() {
  for (let i = 0; i < 4; i++) {
    for (let j = 0; j < 4; j++) {
      document.getElementById("" + i + j).innerHTML = Math.floor(Math.random() * 10);
    }
  }
}
function countdown(seconds) {
  setTimeout(function () { document.getElementById("mybutton").disabled = false; }, 10000);
  var timeleft = seconds;
  var Timer = setInterval(function () {
    document.getElementById("countdown").innerHTML = timeleft + " seconds remaining";
    timeleft -= 1;
    if (timeleft <= 0) {
      clearInterval(Timer);
      document.getElementById("countdown").innerHTML = "Finished"
    }
  }, 1000);
}
function redgreencount(a, b, c) { //The d array and the 3rd arg exist so that each time you click on a cell it registers it as clicked and doesn't doublecount if you press an already 
  //colored cell
  if (a == 1) {
    if (!(d.includes(c))) {
      redcount += 1;
    }
    d.push(c);
  }
  if (b == 1) {
    if (!(d.includes(c))) {
      greencount += 1;
    }
    d.push(c);
  }
}
function colorChange(i, j) {
  if (document.getElementById("" + i + j).innerHTML > 5) {
    document.getElementById("" + i + j).style.backgroundColor = "green";
    redgreencount(0, 1, "" + i + j);
  }
  if (document.getElementById("" + i + j).innerHTML <= 5) {
    document.getElementById("" + i + j).style.backgroundColor = "red";
    redgreencount(1, 0, "" + i + j);
  }
}
function redgreencountprint() {
  document.getElementById("report").innerHTML = "There were " + redcount + " reds and " + greencount + " greens.";
}
function whitifytable() {
  for (let i = 0; i < 4; i++) {
    for (let j = 0; j < 4; j++) {
      document.getElementById("" + i + j).style.backgroundColor = "";
    }
  }
}
function init() {
  d = [];
  redcount = 0;
  greencount = 0;
  whitifytable();
}